# Generated by Django 3.2.16 on 2022-11-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20221109_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Clothes'), ('F', 'Furnitures'), ('BF', 'Baby Food'), ('K', 'Kitchen Utensil')], default='C', max_length=2),
            preserve_default=False,
        ),
    ]
