# Generated by Django 3.2.16 on 2022-11-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_itemvariation_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_variations',
            field=models.ManyToManyField(to='store.ItemVariation'),
        ),
    ]
